upload_dig_new_btn: xpath://button[@name='yt0']
upload_dig_choose_file: xpath://input[@id='new-base-er-employee-image-signature-file_name']
upload_dig_upload_btn: xpath://input[@id='new-base-er-employee-image-signature-form-submit']
upload_dig_check_exist: xpath://td[text()='signatire1.png']
upload_dig_success_notif: xpath://div[@id='jSuccess']
upload_dig_del_btn: xpath://table/tbody//tr[td='signatire1.png']/td/a[@class='delete']
upload_dig_view_btn: xpath://table/tbody//tr[td='signatire1.png']/td/a[@class='view']
upload_dig_adv_btn: xpath://button[@id='search-button'][1]
upload_dig_adv_input: xpath://input[@id='search-base-er-employee-image-signature-file_name']